export const notificationUnreadKey = ["support", "notifications", "unread"] as const;
export const notificationsListKey = ["support", "notifications", "list"] as const;
export const tasksListKey = ["tasks", "list"] as const;
export const profileMeKey = ["auth", "me"] as const;
export const publicProfileKey = (userId: string) => ["profile", "public", userId] as const;
export const achievementsListKey = ["achievements", "catalog"] as const;
export const leaderboardKey = ["leaderboard"] as const;
export const shopItemsKey = ["shop", "items"] as const;
export const shopMeKey = (userId: string | undefined) => ["shop", "me", userId ?? "anon"] as const;
export const giftsPackKey = (userId: string | undefined) => ["gifts", "pack", userId ?? "anon"] as const;
export const adminInboxCountsKey = ["admin", "inbox-counts"] as const;
export const adminTaskSubmissionsKey = ["admin", "tasks", "submissions"] as const;
export const adminSupportSuggestionsKey = ["admin", "support", "suggestions"] as const;
export const adminSupportReportsKey = ["admin", "support", "reports"] as const;
export const adminUsersKey = ["admin", "users"] as const;
export const adminTasksKey = ["admin", "tasks"] as const;
export const adminAchievementsKey = ["admin", "achievements"] as const;
export const adminShopItemsKey = ["admin", "shop", "items"] as const;
export const adminAuditLogsKey = ["admin", "audit-logs"] as const;
export const adminTelegramTemplatesKey = ["admin", "telegram", "templates"] as const;
